##
## EPITECH PROJECT, 2024
## Arcade
## File description:
## Makefile
##

all: $(NAME)

$(NAME):
	make -C sdl2
	make -C sfml
	make -C ncurses

clean :
	make -C sdl2 clean
	make -C sfml clean
	make -C ncurses clean

fclean :
	make -C sdl2 fclean
	make -C sfml fclean
	make -C ncurses fclean

re :
	make -C sdl2 re
	make -C sfml re
	make -C ncurses re
