##
## EPITECH PROJECT, 2024
## Arcade
## File description:
## Makefile
##

SRC = sdl2	\
	  sfml

all: $(NAME)

$(NAME):
	make -C $(SRC)

clean :
	make -C $(SRC) clean

fclean :
	make -C $(SRC) fclean

re :
	make -C $(SRC) re
