##
## EPITECH PROJECT, 2024
## Arcade
## File description:
## Makefile
##

all: $(NAME)

$(NAME):
	make -C sdl2
	make -C sfml

clean :
	make -C sdl2 clean
	make -C sfml clean

fclean :
	make -C sdl2 fclean
	make -C sfml fclean

re :
	make -C sdl2 re
	make -C sfml re
