##
## EPITECH PROJECT, 2024
## Arcade
## File description:
## Makefile
##

all: $(NAME)

$(NAME):
	make -C nibbler
	make -C snake

clean :
	make -C nibbler clean
	make -C snake clean

fclean :
	make -C nibbler fclean
	make -C snake fclean

re :
	make -C nibbler re
	make -C snake re
